pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'github',  
                url: 'https://github.com/nimmadalaprudhvi/Jenkins-Zero-To-Hero',
                branch: 'main'  
                                                                                                  
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Build Docker Image'
                    docker build -t prudhvi-pyt:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push prudhvi-python-project:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'github', 
                url: 'https://github.com/nimmadalaprudhvi/Jenkins-Zero-To-Hero/python-jenkins-argocd-k8s/deploy.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    git credentialsId: 'github', 
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/nimmadalaprudhvi/Jenkins-Zero-To-Hero/python-jenkins-argocd-k8s/deploy.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
